// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the D2 TypeScript catalog codegen — see emitter tests for coverage.
//   Source spec: contracts/auth-context/IAuthContext.spec.json
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/* eslint-disable */

export const ImpersonationKind = {
  Consent: "Consent",
  Force: "Force",
} as const;

export type ImpersonationKind = (typeof ImpersonationKind)[keyof typeof ImpersonationKind];

/** Consent-based impersonation (OTP-authorized). */
export const ImpersonationKind_Consent: ImpersonationKind = ImpersonationKind.Consent;
/** Force impersonation (admin-only, silent). */
export const ImpersonationKind_Force: ImpersonationKind = ImpersonationKind.Force;
