// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the D2 TypeScript catalog codegen — see emitter tests for coverage.
//   Source spec: contracts/auth-context/IAuthContext.spec.json
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/* eslint-disable */

import type { CallPathKind } from "../enums/call-path-kind.g.js";

/**
 * One hop in the propagated call-path. Mirrors .NET CallPathEntry record.
 * Operational telemetry only — authority never reads the call-path. The
 * timestamp is the wire DateTimeOffset ISO string (matching .NET's `O`
 * round-trip format).
 */
export interface CallPathEntry {
  readonly id: string;
  readonly kind: CallPathKind;
  readonly timestamp: string;
}
