// -----------------------------------------------------------------------
// <auto-generated>
//   Generated by the D2 TypeScript catalog codegen — see emitter tests for coverage.
//   Source spec: contracts/auth-scopes/scopes.spec.json
//   Manual edits will be lost on rebuild.
// </auto-generated>
// -----------------------------------------------------------------------

/* eslint-disable */

/**
 * OAuth scope catalog emitted from contracts/auth-scopes/scopes.spec.json.
 * Tree-emitted nested constants — `Scopes.auth.user.impersonate.consent` resolves
 * to the dot-segmented spec name.
 */
export const Scopes = {
  anon: {
    public: {
      health: "anon.public.health",
    },
  },
  self: {
    read: "self.read",
    write: "self.write",
  },
} as const;

/**
 * All declared scopes in spec-sorted order.
 */
export const ALL_SCOPES: readonly string[] = [
  "anon.public.health",
  "self.read",
  "self.write",
];
